# Generated by Django 4.2.13 on 2024-07-25 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_project_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='assingment',
            new_name='assignment',
        ),
        migrations.AddField(
            model_name='project',
            name='hosts',
            field=models.ManyToManyField(related_name='hosts', to=settings.AUTH_USER_MODEL),
        ),
    ]
